# Generated by Django 2.0.4 on 2019-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=100, verbose_name='mimetype'),
        ),
    ]
